library(lattice)
library(datasets)
# plots: xyplot (scatter), bwplot (box-n-whiskers), histogram, stripplot(boxplot with points)
# plots: dotplot (dots on 'violin strings'), splom (scatterplot matrix like 'pairs' in basic plotting)
# plots: levelplot, contourplot (plotting image data)
airquality = transform(airquality, Month = factor(Month))
plot = xyplot(Ozone ~ Wind | Month, data = airquality, layout = c(5, 1))
print(plot)
